# PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/demo
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Profil actif
spring.profiles.active=local
